#MySQL Info

MySQL_host: localhost
MySQL_port: 3306
MySQL_database: test
MySQL_username: root
MySQL_password: password
MySQL_claimData: claim_data
MySQL_permissionData: permission_data

#Other

World_Name: world

Spawn:
    x:
    y:
    z:
    yaw:
    pitch:
    
#Inactivity demotion in days
owner_inactive: 56
member_inactive: 42

#Region limits per role
Limit:
    Builder: 50
    JrBuilder: 15
    
#Height limits
positive_y: 500.0
negative_y: -100.0