#MySQL Info

MySQL_host: localhost
MySQL_port: 3306
MySQL_database: test
MySQL_username: root
MySQL_password: password
MySQL_claimData: claim_data
MySQL_permissionData: permission_data
MySQL_locationData: location_data
MySQL_locationRequestData: location_request_data

region_data: regionData
owner_data: ownerData
member_data: memberData
player_data: playerData

#Other

World_Name: world

Spawn:
    x:
    y:
    z:
    yaw:
    pitch: