#MySQL Info

MySQL_host: localhost
MySQL_port: 3306
MySQL_database: test
MySQL_username: root
MySQL_password: password
MySQL_claimData: claim_data
MySQL_permissionData: permission_data
MySQL_locationData: location_data
MySQL_locationRequestData: location_request_data

region_data: regions
owner_data: region_owners
member_data: region_members
player_data: players
request_data: requests
region_logs: logs
message_data: messages

#Other

World_Name: world

Spawn:
    x:
    y:
    z:
    yaw:
    pitch:
    
#Inactivity demotion in days
owner_inactive: 56
member_inactive: 42