name: EarthServer
version: 2.0
main: me.elgamer.earthserver.Main
description: Claiming System
depend: [WorldEdit, WorldGuard, LuckPerms, Vault]

commands:
    claim:
        usage: /<command> [radius]
        description: Opens the claim gui or claims regions in a radius around the player.
    unclaim:
        usage: /<command> [radius]
        description: Unclaims in a radius around the player, radius null = only regions player is in.
    teamclaim:
        usage: /<command> [radius]
        description: Teamclaims regions in a radius around the player, radius null = only regions player is in.
    addmember:
        usage: /<command> <user> [radius]
        description: Adds a certain player to regions in a radius around the player, radius null = only regions player is in.
    removemember:
        usage: /<command> <user> [radius]
        description: Removes a certain player to regions in a radius around the player, radius null = only regions player is in.       
    public:
        usage: /<command> [radius]
        description: Makes regions public to builders in a radius around the player, radius null = only regions player is in.
    private:
        usage: /<command> [radius]
        description: Makes regions private in a radius around the player, radius null = only regions player is in. 
    adminclaim:
        usage: /adminclaim help
        description: Admin commands for regions, allows unclaiming, transferring ownership, adding/removing members and changing regions to public/private. 
    addtodatabase:
        usage: /addtodatabase [region] [owner-uuid] [public] <members-uuid (comma-separated)>
        description: An admin function to import all data from existing claims stored in the worldguard regions file.
    tpblock:
        usage: /tpblock <x> <y> <z>
        description: Simple command to place teleport command blocks.
    locationrequest:
        usage: /locationRequest <name>
        description: Creates a location request for the teleport gui.
    addlocation:
        usage: /addlocation
        description: Adds the location to the gui
    denyrequest:
        usage: /denyrequest
        description: Denies a location request
    requests:
        usage: /requests
        description: Lists all location requests
    removelocation:
        usage: /removelocation
        description: removes a location from the gui
    navigator:
        usage: /navigator
        description: opens the navigation gui
    torequest:
        usage: /torequest
        description: teleports the player to the exact location where the location was requested