name: EarthServer
version: 1.0
main: me.elgamer.earthserver.Main
description: Claiming System
depend: [WorldEdit, WorldGuard, LuckPerms, Vault]

commands:
    claim:
        usage: /<command> [radius]
        description: Opens the claim gui or claims regions in a radius around the player.
    unclaim:
        usage: /<command> [radius]
        description: Unclaims in a radius around the player, radius null = only regions player is in.
    teamclaim:
        usage: /<command> [radius]
        description: Teamclaims regions in a radius around the player, radius null = only regions player is in.
    addmember:
        usage: /<command> <user> [radius]
        description: Adds a certain player to regions in a radius around the player, radius null = only regions player is in.
    removemember:
        usage: /<command> <user> [radius]
        description: Removes a certain player to regions in a radius around the player, radius null = only regions player is in.       
    public:
        usage: /<command> [radius]
        description: Makes regions public to builders in a radius around the player, radius null = only regions player is in.
    private:
        usage: /<command> [radius]
        description: Makes regions private in a radius around the player, radius null = only regions player is in. 
    adminclaim:
        usage: /adminclaim help
        description: Admin commands for regions, allows unclaiming, transferring ownership, adding/removing members and changing regions to public/private. 
    addtodatabase:
        usage: /addtodatabase [region] [owner-uuid] [public] <members-uuid (comma-separated)>
        description: An admin function to import all data from existing claims stored in the worldguard regions file.
    tpblock:
        usage: /tpblock <x> <y> <z>
        description: Simple command to place teleport command blocks.