name: EarthServer
version: 2.1.0
main: me.elgamer.earthserver.Main
description: Claiming System and Navigation for the Earth server.
depend: [WorldEdit, WorldGuard, LuckPerms, Vault]

commands:
    claim:
        aliases: [claims, claimgui, regiongui, regions]
        usage: /<command>
        description: Opens the claim gui.
    convertclaims:
        usage: /<command>
        description: Converts all old claims to the new system, only works if there are no existing regions.
    fixregions:
        usage: /<command>
    tpblock:
        usage: /tpblock <x> <y> <z>
        description: Simple command to place teleport command blocks.
    locationrequest:
        usage: /locationRequest <name>
        description: Creates a location request for the teleport gui.
    addlocation:
        usage: /addlocation
        description: Adds the location to the gui
    denyrequest:
        usage: /denyrequest
        description: Denies a location request
    requests:
        usage: /requests
        description: Lists all location requests
    removelocation:
        usage: /removelocation
        description: removes a location from the gui
    navigator:
        usage: /navigator
        description: opens the navigation gui
    torequest:
        usage: /torequest
        description: teleports the player to the exact location where the location was requested